export type NICESPList = {
  "@odata.editLink"?: string;
  "@odata.etag"?: string;
  "@odata.id"?: string;
  "@odata.type"?: string;
  Approved?: null | boolean;
  Attachments?: boolean;
  AuthorId?: number;
  ComplianceAssetId?: null | number;
  ContentTypeId?: string;
  Created?: Date;
  CropServiceCompleted?: null | boolean;
  CropServiceRequired?: null | boolean;
  Description?: string;
  EditorId?: number;
  EndCropTime?: number;
  FileSystemObjectType?: number;
  GUID?: string;
  ID?: number;
  Id?: number;
  Modified?: Date;
  OData__ColorTag?: null;
  OData__UIVersionString?: string;
  StartCropTime?: number;
  Tags?: string[];
  Title?: string;
};
